[build]
  base = "vite-project"
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.mp4"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "video/mp4"
